spring.application.name=inventory-order-mgt

# Server
server.port=${PORT:9000}

# PostgreSQL Database (Neon)
spring.datasource.url=jdbc:postgresql://ep-spring-credit-aofn2sli.c-2.ap-southeast-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# JWT
app.jwt.expirationMinutes=${JWT_EXPIRATION_MINUTES:1440}
app.jwt.secret=${JWT_SECRET}

# Swagger
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha
springdoc.swagger-ui.try-it-out-enabled=true